"""

@author: tofo

joint positive direction with respect to exntensor/flexor
"""

posdir_dict = {}

posdir_dict['NeckPitch'] = "E"
posdir_dict['NeckRoll'] = "E"
posdir_dict['NeckYaw'] = "E"
posdir_dict['EyesTilt'] = "E"
posdir_dict['EyesVersion'] = "E"
posdir_dict['EyesVergence'] = "F"
posdir_dict['TorsoYaw'] = "E"
posdir_dict['TorsoRoll'] = "E"
posdir_dict['TorsoPitch'] = "F"
posdir_dict['RShoulderPitch'] = "F"
posdir_dict['RShoulderRoll'] = "E"
posdir_dict['RShoulderYaw'] = "F"
posdir_dict['RElbow'] = "F"
posdir_dict['RWristProsup'] = "F"
posdir_dict['RWristPitch'] = "F"
posdir_dict['RWristYaw'] = "E"
posdir_dict['RHandFinger'] = "F"
posdir_dict['RThumbOppose'] = "F"
posdir_dict['RThumbProximal'] = "F"
posdir_dict['RThumbDistal'] = "F"
posdir_dict['RIndexProximal'] = "F"
posdir_dict['RIndexDistal'] = "F"
posdir_dict['RMiddleProximal'] = "F"
posdir_dict['RMiddleDistal'] = "F"
posdir_dict['RPinky'] = "F"
posdir_dict['RHipPitch'] = "E"
posdir_dict['RHipRoll'] = "E"
posdir_dict['RHipYaw'] = "E"
posdir_dict['RKnee'] = "E"
posdir_dict['RAnklePitch'] = "E"
posdir_dict['RAnkleRoll'] = "E"
posdir_dict['LShoulderPitch'] = "F"
posdir_dict['LShoulderRoll'] = "E"
posdir_dict['LShoulderYaw'] = "F"
posdir_dict['LElbow'] = "F"
posdir_dict['LWristProsup'] = "F"
posdir_dict['LWristPitch'] = "F"
posdir_dict['LWristYaw'] = "E"
posdir_dict['LHandFinger'] = "F"
posdir_dict['LThumbOppose'] = "F"
posdir_dict['LThumbProximal'] = "F"
posdir_dict['LThumbDistal'] = "F"
posdir_dict['LIndexProximal'] = "F"
posdir_dict['LIndexDistal'] = "F"
posdir_dict['LMiddleProximal'] = "F"
posdir_dict['LMiddleDistal'] = "F"
posdir_dict['LPinky'] = "F"
posdir_dict['LHipPitch'] = "E"
posdir_dict['LHipRoll'] = "E"
posdir_dict['LHipYaw'] = "E"
posdir_dict['LKnee'] = "E"
posdir_dict['LAnklePitch'] = "E"
posdir_dict['LAnkleRoll'] = "E"
